# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.extension.date:
        class:  Twig_Extensions_Extension_Date
        arguments:
            - "@translator"
        tags:
             - { name: 'twig.extension' }
